### ISSUE TITLE
aws-greengrass-cloudwatch-metrics: Enhanced support for Batch Metrics Submission

### ISSUE THREAD

**Issue by pvipparl** [aws-greengrass/aws-greengrass-cloudwatch-metrics#11]
---

**Feature Description**

This proposal is to enhance the AWS Greengrass CloudWatch Metrics component to support the publishing of multiple metrics within a single payload. The current implementation restricts the payload to only one metric datum, which can be limiting in scenarios where multiple metrics are collected and need to be sent simultaneously.

**Use Case**

In many monitoring scenarios within IoT and edge computing environments, multiple metrics (such as CPU usage, memory usage, disk I/O, etc.) are collected at the same time. Being able to send these metrics in a single payload would improve efficiency in terms of network usage and data processing. It also reduces the number of network calls made to CloudWatch.

**Proposed Solution**

The solution involves modifying the message handling logic of the AWS Greengrass CloudWatch Metrics component. This entails:

- Updating the message parsing logic to handle an array of metric data in addition to a single datum (maintain backward compatibility).
- Enhancing the message validation logic to ensure each metric datum in the array conforms to the expected format.
- Ensuring backward compatibility, so the component can still handle payloads containing a single metric.

A prototype of this feature has been implemented and tested on an EC2 instance mimicking a Greengrass device. 

**Other**

* [x] :wave: I may be able to implement this feature request
* [ ] :warning: This feature might incur a breaking change

---

**Comment by MikeDombo** [comment]
Hi there, thanks for your post.

This component already does batch metrics you send when sending to CloudWatch metrics. https://github.com/aws-greengrass/aws-greengrass-cloudwatch-metrics/blob/b428cb0ca78ff1f67e346d6d4cce7994f6462860/src/metric/publisher.py#L16.

The input you send using local IPC is not batched, but batching it will not have a meaningful impact since this component batches up internally.

I'd also suggest you consider using the Log Manager component which supports reading and uploading log files containing CloudWatch EMF formatted metrics. These metrics will automatically turn into CloudWatch metrics when ingested to CloudWatch logs

**Comment by MikeDombo** [comment]
No response, closing this issue.

Please reopen if necessary.

**Comment by pvipparl** [comment]
**Re-opening**
Hi Mike,

Thank you for your swift and informative response regarding the batching mechanism in the AWS Greengrass CloudWatch Metrics component.

I would like to further add an aspect of the component functionality, particularly regarding the initial stage of metric collection and transmission. Our proposal aims to enhance the efficiency of the metric sender by batching multiple metrics into a single IPC message before it reaches the AWS Greengrass CloudWatch Metrics component.

### Core Aspects of Our Proposal:
- **Optimized IPC Usage**: Our focus is on reducing the frequency of IPC calls by enabling multiple metrics to be bundled in a single IPC message. We have use cases where there are multiple metrics that are all available at the same time.  Bundling them into a single message to the CloudWatch metrics component reduces the number of messages we need to send and more closely mimics the CloudWatch API.  That may lead to...
- **Enhanced Sender Efficiency**: By allowing batching at the IPC message level, we aim to lower the computational overhead on the sender's side, leading to more efficient resource utilization and potentially improving the overall system performance.

### Our Objective:
While we acknowledge the component's capability to handle batching to CloudWatch, our enhancement is specifically targeted at the initial metric transmission phase. The ability to batch at the IPC message level could significantly streamline the process, particularly for systems that generate metrics at a high rate.

We believe this feature could be a valuable addition to the component. Note that our proposed implementation maintains backward compatibility - the component would still be capable of processing messages containing a single metric.

**Comment by MikeDombo** [comment]
Hi,

Like I mentioned in my first message, batching at the IPC level won't have a meaningful impact. Are you finding that that is actually a bottleneck? Note that this component is limited in what it can do. It sends 1 batch at a time and any IPC message sent while the data is being uploaded to cloudwatch will be blocked.

**Comment by MikeDombo** [comment]
For very high throughput I really would highly recommend using LogManager and EMF https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch_Embedded_Metric_Format_Specification.html instead of this component as this component isn't designed for high throughput.

**Comment by pvipparl** [comment]
Hi Mike

Thank you for your recommendations and we will look into it. I'm closing the issue.
