### ISSUE TITLE
(docs): No mention of coreName dimension that is automatically applied

### ISSUE THREAD

**Issue by AdamVD** [aws-greengrass/aws-greengrass-cloudwatch-metrics#8]
**Describe the bug**
The [AWS Greengrass V2 docs on the CloudWatch metrics component](https://docs.aws.amazon.com/greengrass/v2/developerguide/cloudwatch-metrics-component.html) makes no mention of the `coreName` dimension which is automatically applied by the component. I added a `CoreName` dimension manually before sending my metrics along to this component, only to later find that this was unnecessary.

**Expected behavior**
The component documentation should state that the `coreName` dimension will be automatically applied to any incoming metrics.

**Comment by vabhasin** [comment]
Hello @AdamVD you are right, this is a documentation mistake. Sorry that we missed it and thank you for pointing it out. 
We will add this to our Component docs.

**Comment by saranyailla** [comment]
Hello, 
AWS Greengrass public [documentation](https://docs.aws.amazon.com/greengrass/v2/developerguide/cloudwatch-metrics-component.html#cloudwatch-metrics-component-input-data) is updated to include the suggestion. Closing this issue. Please reopen if you've more concerns. Thank you!
